apiVersion: v1
kind: Namespace
metadata: 
  name: main
...
---
apiVersion: v1
kind: Pod
meatadata:
  name: mypod
  labels: 
    app: myapp
  namespace: main
spec:
  containers:
    - name: nginx-cont
      image: nginx:latest
      ports:
        - name: containerport
          containerPort: 80
...
---
apiVersion: v1
kind: Service
metadata:
  name: ciservice
  labels:
    app: app
spec:
  type: ClusterIP
  selector:
     app: myapp
  ports:
    - name: cisvc-port
      protocol: TCP
      port: 80
      targetPort: 80
...
---