apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-deamon
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: my-temp
      labels:
        app: myapp
    spec:
      conatiners:
        - name: daemon-container
          image: amazon/cloudwatch-agent
          ports:
            - name: containerport
              containerPort: 80