apiVersion: v1
kind: Pod
meatadata: 
  name: my-pod
  labels:
    app: myapp
spec:
  volumes:
    - name: my-vol
  persistentVolumeClaim: 
    claimName: my-pvc
  conatiners:
    - name: my-cont
      image: nginx:latest
      ports:
        - name: cont-port
          conatinerPort: 80
      volumeMounts:
        - name: my-vol
          mountPath: /usr/share/nginx/html