apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels: 
    app: myapp
spec:
  capacity: 
    storage:
  accessMode:
    - ReadWriteOnce
  storageClassName: standard
  volumeMode: filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
